name       : tree-sitter
version    : 0.20.2
release    : 11
source     :
    - https://github.com/tree-sitter/tree-sitter/archive/refs/tags/v0.20.2.tar.gz : 2a0445f8172bbf83db005aedb4e893d394e2b7b33251badd3c94c2c5cc37c403
license    : MIT
component  : programming.library
homepage   : https://tree-sitter.github.io
summary    : An incremental parsing system for programming tools
description: |
    Tree-sitter is a parser generator tool and an incremental parsing library.
optimize   :
    - lto
    - speed
build      : |
    %make
install    : |
    %make_install LIBDIR=%libdir% PREFIX=/usr
    rm -v $installdir/%libdir%/libtree-sitter.a
