name       : tree-sitter
version    : 0.20.6
release    : 13
source     :
    - https://github.com/tree-sitter/tree-sitter/archive/refs/tags/v0.20.6.tar.gz : 4d37eaef8a402a385998ff9aca3e1043b4a3bba899bceeff27a7178e1165b9de
license    : MIT
component  : programming.library
homepage   : https://tree-sitter.github.io
summary    : An incremental parsing system for programming tools
description: |
    Tree-sitter is a parser generator tool and an incremental parsing library.
optimize   :
    - lto
    - speed
build      : |
    %make
install    : |
    %make_install LIBDIR=%libdir% PREFIX=/usr
    rm -v $installdir/%libdir%/libtree-sitter.a
