name       : tree-sitter
version    : 0.20.4
release    : 12
source     :
    - https://github.com/tree-sitter/tree-sitter/archive/refs/tags/v0.20.4.tar.gz : 979ad0b36eb90975baf0c65d155d106276cac08afb1c2fe0ad54d4b7d498ce39
license    : MIT
component  : programming.library
homepage   : https://tree-sitter.github.io
summary    : An incremental parsing system for programming tools
description: |
    Tree-sitter is a parser generator tool and an incremental parsing library.
optimize   :
    - lto
    - speed
build      : |
    %make
install    : |
    %make_install LIBDIR=%libdir% PREFIX=/usr
    rm -v $installdir/%libdir%/libtree-sitter.a
