name       : tree-sitter
version    : 0.18.0
release    : 4
source     :
    - https://github.com/tree-sitter/tree-sitter/archive/0.18.0.tar.gz : 574458dbc8b6761027d3090bc2fd474f17ea77d875d4713ed9260d0def125bce
license    : MIT
component  : programming.library
homepage   : https://tree-sitter.github.io
summary    : An incremental parsing system for programming tools
description: |
    Tree-sitter is a parser generator tool and an incremental parsing library.
optimize   :
    - lto
    - speed
build      : |
    %make
install    : |
    %make_install LIBDIR=%libdir% PREFIX=/usr
    rm -v $installdir/%libdir%/libtree-sitter.a
