name       : tree-sitter
version    : 0.17.1
release    : 2
source     :
    - https://github.com/tree-sitter/tree-sitter/archive/0.17.1.tar.gz : 07b62f5d4408a488589d918676184340ce6b7ee3a0d78ca5b8fb9d31be18eba0
license    : MIT
component  : programming.library
homepage   : https://tree-sitter.github.io
summary    : An incremental parsing system for programming tools
description: |
    Tree-sitter is a parser generator tool and an incremental parsing library.
optimize   :
    - lto
    - speed
build      : |
    %make
install    : |
    %make_install LIBDIR=%libdir% PREFIX=/usr
    rm -v $installdir/%libdir%/libtree-sitter.a
