name       : tree-sitter
version    : 0.20.1
release    : 10
source     :
    - https://github.com/tree-sitter/tree-sitter/archive/refs/tags/v0.20.1.tar.gz : 12a3f7206af3028dbe8a0de50d8ebd6d7010bf762db918acae76fc7585f1258d
license    : MIT
component  : programming.library
homepage   : https://tree-sitter.github.io
summary    : An incremental parsing system for programming tools
description: |
    Tree-sitter is a parser generator tool and an incremental parsing library.
optimize   :
    - lto
    - speed
build      : |
    %make
install    : |
    %make_install LIBDIR=%libdir% PREFIX=/usr
    rm -v $installdir/%libdir%/libtree-sitter.a
