name       : tree-sitter
version    : 0.16.9
release    : 1
source     :
    - https://github.com/tree-sitter/tree-sitter/archive/0.16.9.tar.gz : 203747f99569120286809a74d30954a8538e8f54fab7bc09ee355f59d27ab972
license    : MIT
component  : programming.library
homepage   : https://tree-sitter.github.io
summary    : An incremental parsing system for programming tools
description: |
    Tree-sitter is a parser generator tool and an incremental parsing library.
optimize   :
    - lto
    - speed
build      : |
    %make
install    : |
    %make_install LIBDIR=%libdir% PREFIX=/usr
    rm -v $installdir/%libdir%/libtree-sitter.a
