name       : tree-sitter
version    : 0.20.7
release    : 14
source     :
    - https://github.com/tree-sitter/tree-sitter/archive/refs/tags/v0.20.7.tar.gz : b355e968ec2d0241bbd96748e00a9038f83968f85d822ecb9940cbe4c42e182e
license    : MIT
component  : programming.library
homepage   : https://tree-sitter.github.io
summary    : An incremental parsing system for programming tools
description: |
    Tree-sitter is a parser generator tool and an incremental parsing library.
optimize   :
    - lto
    - speed
build      : |
    %make
install    : |
    %make_install LIBDIR=%libdir% PREFIX=/usr
    rm -v $installdir/%libdir%/libtree-sitter.a
