name       : tree-sitter
version    : 0.18.3
release    : 6
source     :
    - https://github.com/tree-sitter/tree-sitter/archive/v0.18.3.tar.gz : 0803a19426aa98a06fd7fae817b72e7c3ce8684f3383870e2bd087a35d2b5612
license    : MIT
component  : programming.library
homepage   : https://tree-sitter.github.io
summary    : An incremental parsing system for programming tools
description: |
    Tree-sitter is a parser generator tool and an incremental parsing library.
optimize   :
    - lto
    - speed
build      : |
    %make
install    : |
    %make_install LIBDIR=%libdir% PREFIX=/usr
    rm -v $installdir/%libdir%/libtree-sitter.a
