name       : tree-sitter
version    : 0.19.5
release    : 8
source     :
    - https://github.com/tree-sitter/tree-sitter/archive/refs/tags/v0.19.5.tar.gz : 953edda5a21423cbfd916dbb1b1552a12f7ab649728846b5a1fb49483672e82b
license    : MIT
component  : programming.library
homepage   : https://tree-sitter.github.io
summary    : An incremental parsing system for programming tools
description: |
    Tree-sitter is a parser generator tool and an incremental parsing library.
optimize   :
    - lto
    - speed
build      : |
    %make
install    : |
    %make_install LIBDIR=%libdir% PREFIX=/usr
    rm -v $installdir/%libdir%/libtree-sitter.a
