name       : tree-sitter
version    : 0.20.8
release    : 15
source     :
    - https://github.com/tree-sitter/tree-sitter/archive/refs/tags/v0.20.8.tar.gz : 6181ede0b7470bfca37e293e7d5dc1d16469b9485d13f13a605baec4a8b1f791
license    : MIT
component  : programming.library
homepage   : https://tree-sitter.github.io
summary    : An incremental parsing system for programming tools
description: |
    Tree-sitter is a parser generator tool and an incremental parsing library.
optimize   :
    - lto
    - speed
build      : |
    %make
install    : |
    %make_install LIBDIR=%libdir% PREFIX=/usr
    rm -v $installdir/%libdir%/libtree-sitter.a
