name       : tree-sitter
version    : 0.20.0
release    : 9
source     :
    - https://github.com/tree-sitter/tree-sitter/archive/refs/tags/v0.20.0.tar.gz : 4a8070b9de17c3b8096181fe8530320ab3e8cca685d8bee6a3e8d164b5fb47da
license    : MIT
component  : programming.library
homepage   : https://tree-sitter.github.io
summary    : An incremental parsing system for programming tools
description: |
    Tree-sitter is a parser generator tool and an incremental parsing library.
optimize   :
    - lto
    - speed
build      : |
    %make
install    : |
    %make_install LIBDIR=%libdir% PREFIX=/usr
    rm -v $installdir/%libdir%/libtree-sitter.a
